'use client';

import { createContext, useContext, useEffect, useLayoutEffect, useState } from 'react';

const useIsomorphicLayoutEffect = typeof window !== 'undefined' ? useLayoutEffect : useEffect;
import type { Language } from '@/types';

const translations = {
  en: {
    // Navbar / Brand
    brand: 'Nexora Care',
    brandTagline: '',
    navigation: 'Navigation',
    dashboard: 'Dashboard',
    clients: 'Clients',
    customers: 'Customers',
    treatments: 'Treatments',
    specialists: 'Specialists',
    bookings: 'Bookings',
    appointments: 'Appointments',
    ourTeam: 'Our Team',
    profile: 'Profile',
    permissions: 'Permissions',
    backup: 'Backups',
    signOut: 'Sign out',
    logout: 'Logout',
    users: 'Users',
    serviceProviders: 'Service Providers',
    staffAbsenceNav: 'Vacation',
    callLogsNav: 'Call Logs',
    activeBranch: 'Active Branch',
    allBranches: 'All Branches',
    viewAllData: 'View all data',
    theme: 'Theme',

    // Dashboard
    welcomeBack: 'Welcome back',
    overviewToday: "Here's your overview at a glance",
    totalRevenue: 'Total Revenue',
    totalClients: 'Total Clients',
    totalTreatments: 'Total Treatments',
    totalSpecialists: 'Total Specialists',
    totalBookings: 'Total Bookings',
    upcomingAppointments: 'Upcoming Appointments',
    recentBookings: 'Recent Bookings',
    today: 'Today',
    viewAll: 'View all',
    noUpcoming: 'No upcoming appointments',
    client: 'Client',
    treatment: 'Treatment',
    specialist: 'Specialist',
    dateTime: 'Date & Time',
    status: 'Status',

    // Clients / Customers
    clientDirectory: 'Client Directory',
    newClient: 'New Client',
    searchClients: 'Search clients…',
    name: 'Name',
    email: 'Email',
    phone: 'Phone',
    actions: 'Actions',
    noClients: 'No clients found.',
    addClient: 'Add Client',
    editClient: 'Edit Client',
    clientName: 'Client Name',
    clientEmail: 'Email (optional)',
    clientPhone: 'Phone Number',
    save: 'Save',
    cancel: 'Cancel',
    deleteConfirm: 'Delete this client?',

    // Treatments / Services
    treatmentMenu: 'Treatment Menu',
    newTreatment: 'New Service',
    searchTreatments: 'Search treatments…',
    service: 'Treatment',
    services: 'Services',
    price: 'Price',
    addTreatment: 'Add Treatment',
    editTreatment: 'Edit Treatment',
    serviceName: 'Treatment Name',
    servicePrice: 'Price (USD)',
    deleteTreatmentConfirm: 'Delete this treatment?',
    noTreatments: 'No treatments found.',

    // Specialists / Providers
    specialistRoster: 'Specialist Roster',
    providers: 'Providers',
    newSpecialist: 'New Specialist',
    searchSpecialists: 'Search specialists…',
    type: 'Type',
    addSpecialist: 'Add Specialist',
    editSpecialist: 'Edit Specialist',
    specialistName: 'Specialist Name',
    specialistType: 'Specialisation',
    deleteSpecialistConfirm: 'Delete this specialist?',
    noSpecialists: 'No specialists found.',
    bio: 'Bio',
    photo: 'Photo',
    choosePhoto: 'Choose Photo',
    changePhoto: 'Change',
    removePhoto: 'Remove',
    providerCreated: 'Specialist created',
    providerUpdated: 'Specialist updated',

    // Branches / Reports / Messages / Staff Absence
    branches: 'Branches',
    payments: 'Payments',
    reports: 'Reports',
    messages: 'Messages',
    staffAbsence: 'Vacation',
    callLogs: 'Call Logs',

    // Appointments / Bookings
    bookingSchedule: 'Booking Schedule',
    newBooking: 'New Appointment',
    searchBookings: 'Search bookings…',
    allStatuses: 'All',
    scheduled: 'Scheduled',
    completed: 'Completed',
    cancelled: 'Cancelled',
    noShow: 'No Show',
    noShows: 'No-show',
    paid: 'Paid',
    unpaid: 'Unpaid',
    addBooking: 'Add Booking',
    editBooking: 'Edit Booking',
    bookingClient: 'Client',
    bookingTreatment: 'Treatment',
    bookingSpecialist: 'Specialist',
    bookingDate: 'Date & Time',
    bookingStatus: 'Status',
    deleteBookingConfirm: 'Permanently delete this booking?',
    cancelBookingConfirm: 'Cancel this booking? The appointment will be marked as cancelled.',
    noBookings: 'No bookings found.',
    date: 'Date',

    // Profile
    profileSettings: 'Profile & Settings',
    profileSubtitle: 'Manage your account details and password',
    accountInfo: 'Account Information',
    usernameLabel: 'Username',
    emailLabel: 'Email Address',
    phoneLabel: 'Phone Number',
    emailPlaceholder: 'your@email.com',
    phonePlaceholder: '+1 555 000 0000',
    saveChanges: 'Save Changes',
    saving: 'Saving…',
    changePassword: 'Change Password',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    updatePassword: 'Update Password',
    updating: 'Updating…',
    profileUpdated: 'Profile updated successfully.',
    passwordUpdated: 'Password changed successfully.',

    // Login
    loginTitle: 'Welcome Back',
    loginSubtitle: 'Sign in to Nexora Care',
    username: 'Username',
    password: 'Password',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot password?',
    signIn: 'Sign In',
    signingIn: 'Signing in…',
    dividerText: '✦ Nexora Care ✦',

    // Forgot password modal
    resetPassword: 'Reset Password',
    resetStep1Title: 'Forgot Password',
    resetStep1Sub: "Enter your account email and we'll send you a reset code.",
    enterEmail: 'Email Address',
    sendCode: 'Send Code',
    sending: 'Sending…',
    resetStep2Title: 'Enter Reset Code',
    resetStep2Sub: 'Check your email (and SMS if configured) for the 6-digit code.',
    verificationCode: 'Verification Code',
    codePlaceholder: '000000',
    newPasswordLabel: 'New Password',
    passwordStrength: 'Password strength',
    strengthLabels: ['', 'Weak', 'Fair', 'Good', 'Strong'] as string[],
    verifyAndReset: 'Verify & Reset',
    verifying: 'Verifying…',
    resetStep3Title: 'Password Reset!',
    resetStep3Sub: 'Your password has been updated. You can now sign in.',
    backToLogin: 'Back to Login',

    // Client History
    clientHistory: 'Client History',

    // Table / List headers
    customer: 'Customer',
    amount: 'Amount',
    payment: 'Payment',
    serviceStatus: 'Service',
    startDate: 'Start Date',
    endDate: 'End Date',
    duration: 'Duration',
    reason: 'Reason',
    recordAbsence: 'Record Vacation',
    recordVacation: 'Record Vacation',
    vacationManagement: 'Vacation & leave management',
    noAbsenceRecords: 'No vacation records',
    addBranch: 'Add Branch',
    editBranch: 'Edit Branch',
    branchName: 'Branch Name (English)',
    branchNameAr: 'Branch Name (Arabic)',
    address: 'Address',
    staff: 'Staff',
    appts: 'Appts',
    noBranches: 'No branches yet',
    addService: 'Add Service',
    editService: 'Edit Service',
    serviceName2: 'Service Name',
    description: 'Description',
    perSession: 'per session',
    noServices: 'No services found',
    icon: 'Icon',
    serviceCreated: 'Service created',
    serviceUpdated: 'Service updated',
    serviceNameEn: 'English Name',
    serviceNameAr: 'Arabic Name',
    addUser: 'Add User',
    newUser: 'New User',
    editUser: 'Edit User',
    createUser: 'Create User',
    deleteUser: 'Delete User',
    searchUsers: 'Search by username, email, phone…',
    allRoles: 'All Roles',
    noBranchAssigned: 'No branch assigned',
    userCreated: 'User created',
    userUpdated: 'User updated',
    userDeleted: 'User deleted',
    keepPasswordBlank: 'New Password (leave blank to keep)',
    passwordRequired: 'Password is required for new users',
    passwordMinLength: 'Password must be at least 6 characters',
    passwordMin6Placeholder: 'Min 6 characters',
    role: 'Role',
    joined: 'Joined',
    noUsers: 'No users found',
    newAppointment: 'New Appointment',
    noAppointments: 'No appointments found',
    ok: 'OK',
    dateTimeRequired: 'Please select a date and time',
    deleted: 'Deleted',
    failedToDelete: 'Failed to delete',
    editAppt: 'Edit Appointment',
    createAppt: 'Create Appointment',
    dateTimeLabel: 'Date & Time',
    notes: 'Notes',
    notesPlaceholder: 'Optional notes…',
    editDetails: 'Edit Details',
    markComplete: 'Mark Complete',
    startService: 'Start Service',
    deliverService: 'Deliver Service',
    revertPayment: 'Revert Payment',
    reschedule: 'Reschedule',
    apptCreated: 'Appointment created',
    apptUpdated: 'Appointment updated',
    updatedSuccess: 'Updated successfully',
    pending: 'Pending',
    inProgress: 'In Progress',
    partialLabel: 'Partial',

    // Customers page
    broadcast: 'Broadcast',
    allCalls: 'All Calls',
    clearAll: 'Clear All',
    yesClear: 'Yes, clear',
    clearing: 'Clearing…',
    noCallLogs: 'No call logs found',
    branch: 'Branch',
    visits: 'Visits',
    history: 'History',
    noBranch: 'No branch',
    noAppointmentHistory: 'No appointment history',
    close: 'Close',
    sendWhatsapp: 'Send WhatsApp Message',
    sendToPhone: 'Send to (phone number)',
    deleteCustomer: 'Delete Customer',
    deleteWarning: 'You are about to permanently delete',
    deleteWarningText: 'This action is permanent and cannot be undone. All appointments and data linked to this customer will be removed.',
    deleting: 'Deleting…',
    noCallHistory: 'No call history',
    unknownDuration: 'Unknown duration',
    emailTo: 'Email to',
    smsTo: 'SMS to',
    broadcastMessage: 'Broadcast Message',
    selectRecipients: 'Select Recipients',
    compose: 'Compose',
    subject: 'Subject',
    message: 'Message',
    allCustomersLabel: 'All customers',
    callConnecting: 'Connecting…',
    callRinging: 'Ringing…',
    callOnCall: 'On Call',
    callEnded: 'Call Ended',
    endCall: 'End Call',
    sendEmail: 'Send Email',
    sendSms: 'Send SMS',
    permanent: 'permanent',
    to: 'To',
    selectCustomer: 'Select customer…',
    selectService: 'Select service…',
    selectSpecialist: 'Select specialist…',
    unknown: 'Unknown',
    reschedulingFor: 'Rescheduling for',
    deleteApptFor: 'Delete appointment for',
    recordPayment: 'Record Payment',
    paymentMethod: 'Payment Method',
    amountUsd: 'Amount ($)',
    confirmPayment: 'Confirm Payment',
    serviceDelivery: 'Service Delivery',
    deliveryStatus: 'Delivery Status',
    deliveryNotes: 'Delivery Notes',
    nextVisitDate: 'Next Visit Date',
    saveDelivery: 'Save Delivery',
    delivered: 'Delivered',
    partiallyDelivered: 'Partially Delivered',
    notDelivered: 'Not Delivered',
    deliveryNotesPlaceholder: 'Notes about delivery…',
    nextVisitPlaceholder: 'e.g. 2 weeks',
    rescheduleAppt: 'Reschedule Appointment',
    newDateTimeLabel: 'New Date & Time',
    confirmReschedule: 'Confirm Reschedule',
    deleteAppt: 'Delete Appointment',
    deleteApptConfirm: 'This cannot be undone.',
    waReminderName: 'Check-in Reminder',
    waBookName: 'Book Appointment',
    waOfferName: 'Special Offer',
    waReminderText: (name: string) => `Hi ${name}! 👋 This is a reminder for your upcoming appointment at NexoraCare. Please let us know if you need to reschedule. We look forward to seeing you! ✨`,
    waBookText: (name: string) => `Hi ${name}! We'd love to see you again at NexoraCare. Ready to book your next appointment? Click here to schedule: [link] 💆`,
    waOfferText: (name: string) => `Hi ${name}! 🎉 We have an exclusive offer just for you! Get 20% off your next visit this week. Call us or book online. Limited slots available!`,
    emailNotConfigured: 'Email (SendGrid) is not configured. Add API keys in .env.local to send real emails.',
    smsNotConfigured: 'SMS (Twilio) is not configured. Add API keys in .env.local to send real SMS.',
    includeCountryCode: 'Include country code, e.g. +962 for Jordan',
    msgPlaceholder: 'Message from Nexora Care',
    bookingBreakdown: 'Booking Breakdown',
    nSelected: 'selected',
    clearSelection: 'Clear',
    sentSuccess: 'Sent!',
    smsDelivered: 'SMS delivered',
    emailsDelivered: 'emails delivered',
    sendTo: 'Send to',
    allOf: 'all',

    // Common
    loading: 'Loading…',
    error: 'Error',
    required: 'This field is required',
    noEmail: 'No email',
    noPhone: 'No phone',
    edit: 'Edit',
    delete: 'Delete',
    add: 'Add',
    failedToSave: 'Failed to save',
    roleAdmin: 'Admin',
    roleStaff: 'Staff',
    roleManager: 'Manager',
    editAbsence: 'Edit Absence',
    absenceUpdated: 'Absence updated',
    branchNameRequired: 'Branch name is required',
    branchUpdated: 'Branch updated',
    branchCreated: 'Branch created',
    datesRequired: 'Start and end dates are required',
    absenceRecorded: 'Absence recorded',
    deleteRecord: 'Delete Record',
    deleteAbsenceConfirm: 'Delete this absence record? This cannot be undone.',
    searchByCustomer: 'Search by customer…',
    callCompleted: 'Completed',
    callNoAnswer: 'No Answer',
    callFailed: 'Failed',
    day: 'day',
    days: 'days',
    recorded: 'recorded',
    search: 'Search',
    cancelAction: 'Cancel Booking',
    booked: 'Booked',
    welcome: 'Welcome back',
    totalCollected: 'Total collected',
    searchPayments: 'Search payments…',
    method: 'Method',
    noPayments: 'No payments found',
    rolesNav: 'Roles',
    rolesTitle: 'Role Management',
    rolesSub: 'Assign roles to users to control their access level',
    changeRole: 'Change Role',
    roleChanged: 'Role updated',
    roleChangeFailed: 'Failed to update role',
    usersInRole: 'users',
    noUsersInRole: 'No users assigned',
    confirmRoleChange: 'Change role to',
    thisWeek: 'This Week',
    thisMonth: 'This Month',
    revenueOverview: 'Revenue Overview',
    avgPerAppointment: 'Avg per Appointment',
    unpaidInvoices: 'Unpaid Invoices',
    paymentRate: 'Payment Rate',
    appointmentMetrics: 'Appointment Metrics',
    todaysSchedule: "Today's Schedule",
    noShowRate: 'No-Show Rate',
    operations: 'Operations',
    servicesOffered: 'Services Offered',
    revenuePerCustomer: 'Revenue per Customer',
    reportsSubtitle: 'Insights for your wellness center',
    print: 'Print',
    printReport: 'Print Report',

    // Calendar
    calendarNav: 'Calendar',
    revenueNav: 'Revenue',
  },

  ar: {
    // Navbar / Brand
    brand: 'Nexora Care',
    brandTagline: '',
    navigation: 'التنقل',
    dashboard: 'لوحة التحكم',
    clients: 'العملاء',
    customers: 'العملاء',
    treatments: 'العلاجات',
    specialists: 'المتخصصون',
    bookings: 'الحجوزات',
    appointments: 'المواعيد',
    ourTeam: 'فريقنا',
    profile: 'الملف الشخصي',
    permissions: 'الصلاحيات',
    backup: 'النسخ الاحتياطية',
    signOut: 'تسجيل الخروج',
    logout: 'تسجيل الخروج',
    users: 'المستخدمون',
    serviceProviders: 'مزودو الخدمة',
    staffAbsenceNav: 'الإجازات',
    callLogsNav: 'سجل المكالمات',
    activeBranch: 'الفرع النشط',
    allBranches: 'جميع الفروع',
    viewAllData: 'عرض كل البيانات',
    theme: 'السمة',

    // Dashboard
    welcomeBack: 'مرحباً بعودتك',
    overviewToday: 'نظرة عامة على مركز التجميل',
    totalRevenue: 'إجمالي الإيرادات',
    totalClients: 'إجمالي العملاء',
    totalTreatments: 'إجمالي العلاجات',
    totalSpecialists: 'إجمالي المتخصصين',
    totalBookings: 'إجمالي الحجوزات',
    upcomingAppointments: 'المواعيد القادمة',
    recentBookings: 'الحجوزات الأخيرة',
    today: 'اليوم',
    viewAll: 'عرض الكل',
    noUpcoming: 'لا توجد مواعيد قادمة',
    client: 'العميل',
    treatment: 'العلاج',
    specialist: 'المتخصص',
    dateTime: 'التاريخ والوقت',
    status: 'الحالة',

    // Clients / Customers
    clientDirectory: 'دليل العملاء',
    newClient: 'عميل جديد',
    searchClients: 'البحث عن عميل…',
    name: 'الاسم',
    email: 'البريد الإلكتروني',
    phone: 'الهاتف',
    actions: 'الإجراءات',
    noClients: 'لا يوجد عملاء.',
    addClient: 'إضافة عميل',
    editClient: 'تعديل عميل',
    clientName: 'اسم العميل',
    clientEmail: 'البريد الإلكتروني (اختياري)',
    clientPhone: 'رقم الهاتف',
    save: 'حفظ',
    cancel: 'إلغاء',
    deleteConfirm: 'حذف هذا العميل؟',

    // Treatments / Services
    treatmentMenu: 'قائمة العلاجات',
    newTreatment: 'علاج جديد',
    searchTreatments: 'البحث عن علاج…',
    service: 'العلاج',
    services: 'الخدمات',
    price: 'السعر',
    addTreatment: 'إضافة علاج',
    editTreatment: 'تعديل علاج',
    serviceName: 'اسم العلاج',
    servicePrice: 'السعر (دولار)',
    deleteTreatmentConfirm: 'حذف هذا العلاج؟',
    noTreatments: 'لا توجد علاجات.',

    // Specialists / Providers
    specialistRoster: 'قائمة المتخصصين',
    providers: 'مزودو الخدمة',
    newSpecialist: 'متخصص جديد',
    searchSpecialists: 'البحث عن متخصص…',
    type: 'التخصص',
    addSpecialist: 'إضافة متخصص',
    editSpecialist: 'تعديل متخصص',
    specialistName: 'اسم المتخصص',
    specialistType: 'التخصص',
    deleteSpecialistConfirm: 'حذف هذا المتخصص؟',
    noSpecialists: 'لا يوجد متخصصون.',
    bio: 'السيرة الذاتية',
    photo: 'الصورة',
    choosePhoto: 'اختر صورة',
    changePhoto: 'تغيير',
    removePhoto: 'إزالة',
    providerCreated: 'تمت إضافة المتخصص',
    providerUpdated: 'تم تحديث المتخصص',

    // Branches / Reports / Messages / Staff Absence
    branches: 'الفروع',
    payments: 'المدفوعات',
    reports: 'التقارير',
    messages: 'الرسائل',
    staffAbsence: 'الإجازات',
    callLogs: 'سجل المكالمات',

    // Appointments / Bookings
    bookingSchedule: 'جدول الحجوزات',
    newBooking: 'حجز جديد',
    searchBookings: 'البحث عن حجز…',
    allStatuses: 'الكل',
    scheduled: 'مجدول',
    completed: 'مكتمل',
    cancelled: 'ملغى',
    noShow: 'لم يحضر',
    noShows: 'لم يحضر',
    paid: 'مدفوع',
    unpaid: 'غير مدفوع',
    addBooking: 'إضافة حجز',
    editBooking: 'تعديل حجز',
    bookingClient: 'العميل',
    bookingTreatment: 'العلاج',
    bookingSpecialist: 'المتخصص',
    bookingDate: 'التاريخ والوقت',
    bookingStatus: 'الحالة',
    deleteBookingConfirm: 'حذف هذا الحجز نهائياً؟',
    cancelBookingConfirm: 'إلغاء هذا الحجز؟ سيتم تغيير حالته إلى ملغى.',
    noBookings: 'لا توجد حجوزات.',
    date: 'التاريخ',

    // Profile
    profileSettings: 'الملف الشخصي والإعدادات',
    profileSubtitle: 'إدارة تفاصيل حسابك وكلمة المرور',
    accountInfo: 'معلومات الحساب',
    usernameLabel: 'اسم المستخدم',
    emailLabel: 'البريد الإلكتروني',
    phoneLabel: 'رقم الهاتف',
    emailPlaceholder: 'بريدك@example.com',
    phonePlaceholder: '+966 5X XXX XXXX',
    saveChanges: 'حفظ التغييرات',
    saving: 'جاري الحفظ…',
    changePassword: 'تغيير كلمة المرور',
    currentPassword: 'كلمة المرور الحالية',
    newPassword: 'كلمة المرور الجديدة',
    updatePassword: 'تحديث كلمة المرور',
    updating: 'جاري التحديث…',
    profileUpdated: 'تم تحديث الملف الشخصي بنجاح.',
    passwordUpdated: 'تم تغيير كلمة المرور بنجاح.',

    // Login
    loginTitle: 'مرحباً بعودتك',
    loginSubtitle: 'تسجيل الدخول إلى مركز التجميل',
    username: 'اسم المستخدم',
    password: 'كلمة المرور',
    rememberMe: 'تذكرني',
    forgotPassword: 'نسيت كلمة المرور؟',
    signIn: 'تسجيل الدخول',
    signingIn: 'جاري تسجيل الدخول…',
    dividerText: '🌸 صالون · سبا · عيادة',

    // Forgot password modal
    resetPassword: 'إعادة تعيين كلمة المرور',
    resetStep1Title: 'نسيت كلمة المرور',
    resetStep1Sub: 'أدخل بريدك الإلكتروني وسنرسل لك رمز إعادة التعيين.',
    enterEmail: 'البريد الإلكتروني',
    sendCode: 'إرسال الرمز',
    sending: 'جاري الإرسال…',
    resetStep2Title: 'أدخل رمز التحقق',
    resetStep2Sub: 'تحقق من بريدك الإلكتروني (والرسائل القصيرة إن أمكن) للرمز المكون من 6 أرقام.',
    verificationCode: 'رمز التحقق',
    codePlaceholder: '000000',
    newPasswordLabel: 'كلمة المرور الجديدة',
    passwordStrength: 'قوة كلمة المرور',
    strengthLabels: ['', 'ضعيفة', 'مقبولة', 'جيدة', 'قوية'] as string[],
    verifyAndReset: 'تحقق وإعادة التعيين',
    verifying: 'جاري التحقق…',
    resetStep3Title: 'تمت إعادة التعيين!',
    resetStep3Sub: 'تم تحديث كلمة المرور. يمكنك الآن تسجيل الدخول.',
    backToLogin: 'العودة لتسجيل الدخول',

    // Client History
    clientHistory: 'ملف العميل',

    // Table / List headers
    customer: 'العميل',
    amount: 'المبلغ',
    payment: 'الدفع',
    serviceStatus: 'الخدمة',
    startDate: 'تاريخ البداية',
    endDate: 'تاريخ النهاية',
    duration: 'المدة',
    reason: 'السبب',
    recordAbsence: 'تسجيل إجازة',
    recordVacation: 'تسجيل إجازة',
    vacationManagement: 'إدارة الإجازات والغياب',
    noAbsenceRecords: 'لا توجد سجلات إجازات',
    addBranch: 'إضافة فرع',
    editBranch: 'تعديل فرع',
    branchName: 'اسم الفرع (إنجليزي)',
    branchNameAr: 'اسم الفرع (عربي)',
    address: 'العنوان',
    staff: 'الموظفون',
    appts: 'المواعيد',
    noBranches: 'لا توجد فروع بعد',
    addService: 'إضافة خدمة',
    editService: 'تعديل خدمة',
    serviceName2: 'اسم الخدمة',
    description: 'الوصف',
    perSession: 'لكل جلسة',
    noServices: 'لا توجد خدمات',
    icon: 'الأيقونة',
    serviceCreated: 'تمت إضافة الخدمة',
    serviceUpdated: 'تم تحديث الخدمة',
    serviceNameEn: 'الاسم بالإنجليزية',
    serviceNameAr: 'الاسم بالعربية',
    addUser: 'إضافة مستخدم',
    newUser: 'مستخدم جديد',
    editUser: 'تعديل مستخدم',
    createUser: 'إنشاء مستخدم',
    deleteUser: 'حذف مستخدم',
    searchUsers: 'البحث بالاسم أو البريد أو الهاتف…',
    allRoles: 'كل الأدوار',
    noBranchAssigned: 'بلا فرع',
    userCreated: 'تم إنشاء المستخدم',
    userUpdated: 'تم تحديث المستخدم',
    userDeleted: 'تم حذف المستخدم',
    keepPasswordBlank: 'كلمة مرور جديدة (اتركها فارغة للإبقاء)',
    passwordRequired: 'كلمة المرور مطلوبة للمستخدمين الجدد',
    passwordMinLength: 'يجب أن تتكون من 6 أحرف على الأقل',
    passwordMin6Placeholder: 'الحد الأدنى 6 أحرف',
    role: 'الدور',
    joined: 'انضم',
    noUsers: 'لا يوجد مستخدمون',
    newAppointment: 'موعد جديد',
    noAppointments: 'لا توجد مواعيد',
    ok: 'موافق',
    dateTimeRequired: 'يرجى اختيار التاريخ والوقت',
    deleted: 'تم الحذف',
    failedToDelete: 'فشل الحذف',
    editAppt: 'تعديل الموعد',
    createAppt: 'إنشاء موعد',
    dateTimeLabel: 'التاريخ والوقت',
    notes: 'الملاحظات',
    notesPlaceholder: 'ملاحظات اختيارية…',
    editDetails: 'تعديل التفاصيل',
    markComplete: 'تعيين كمكتمل',
    startService: 'بدء الخدمة',
    deliverService: 'تسليم الخدمة',
    revertPayment: 'إلغاء الدفع',
    reschedule: 'إعادة الجدولة',
    apptCreated: 'تم إنشاء الموعد',
    apptUpdated: 'تم تحديث الموعد',
    updatedSuccess: 'تم التحديث بنجاح',
    pending: 'قيد الانتظار',
    inProgress: 'قيد التنفيذ',
    partialLabel: 'جزئي',

    // Customers page
    broadcast: 'إرسال جماعي',
    allCalls: 'كل المكالمات',
    clearAll: 'مسح الكل',
    yesClear: 'نعم، امسح',
    clearing: 'جاري المسح…',
    noCallLogs: 'لا توجد سجلات مكالمات',
    branch: 'الفرع',
    visits: 'الزيارات',
    history: 'السجل',
    noBranch: 'بلا فرع',
    noAppointmentHistory: 'لا يوجد سجل مواعيد',
    close: 'إغلاق',
    sendWhatsapp: 'إرسال رسالة واتساب',
    sendToPhone: 'إرسال إلى (رقم الهاتف)',
    deleteCustomer: 'حذف العميل',
    deleteWarning: 'أنت على وشك الحذف النهائي لـ',
    deleteWarningText: 'هذا الإجراء دائم ولا يمكن التراجع عنه. سيتم حذف جميع المواعيد والبيانات المرتبطة بهذا العميل.',
    deleting: 'جاري الحذف…',
    noCallHistory: 'لا يوجد سجل مكالمات',
    unknownDuration: 'مدة غير معروفة',
    emailTo: 'بريد إلى',
    smsTo: 'رسالة إلى',
    broadcastMessage: 'رسالة جماعية',
    selectRecipients: 'اختر المستلمين',
    compose: 'إنشاء الرسالة',
    subject: 'الموضوع',
    message: 'الرسالة',
    allCustomersLabel: 'كل العملاء',
    callConnecting: 'جاري الاتصال…',
    callRinging: 'يرن…',
    callOnCall: 'في المكالمة',
    callEnded: 'انتهت المكالمة',
    endCall: 'إنهاء المكالمة',
    sendEmail: 'إرسال البريد',
    sendSms: 'إرسال الرسالة',
    permanent: 'دائم',
    to: 'إلى',
    selectCustomer: 'اختر عميل…',
    selectService: 'اختر خدمة…',
    selectSpecialist: 'اختر متخصص…',
    unknown: 'غير معروف',
    reschedulingFor: 'إعادة جدولة لـ',
    deleteApptFor: 'حذف موعد لـ',
    recordPayment: 'تسجيل الدفع',
    paymentMethod: 'طريقة الدفع',
    amountUsd: 'المبلغ ($)',
    confirmPayment: 'تأكيد الدفع',
    serviceDelivery: 'تسليم الخدمة',
    deliveryStatus: 'حالة التسليم',
    deliveryNotes: 'ملاحظات التسليم',
    nextVisitDate: 'تاريخ الزيارة القادمة',
    saveDelivery: 'حفظ التسليم',
    delivered: 'تم التسليم',
    partiallyDelivered: 'تسليم جزئي',
    notDelivered: 'لم يُسلَّم',
    deliveryNotesPlaceholder: 'ملاحظات حول التسليم…',
    nextVisitPlaceholder: 'مثال: أسبوعان',
    rescheduleAppt: 'إعادة جدولة الموعد',
    newDateTimeLabel: 'التاريخ والوقت الجديد',
    confirmReschedule: 'تأكيد إعادة الجدولة',
    deleteAppt: 'حذف الموعد',
    deleteApptConfirm: 'لا يمكن التراجع عن هذا الإجراء.',
    waReminderName: 'تذكير بالموعد',
    waBookName: 'حجز موعد',
    waOfferName: 'عرض خاص',
    waReminderText: (name: string) => `مرحباً ${name}! 👋 هذا تذكير بموعدك القادم في NexoraCare. أخبرنا إن أردت إعادة الجدولة. نتطلع لرؤيتك! ✨`,
    waBookText: (name: string) => `مرحباً ${name}! نود رؤيتك مجدداً في NexoraCare. هل أنت مستعد لحجز موعدك القادم؟ احجز الآن: [رابط] 💆`,
    waOfferText: (name: string) => `مرحباً ${name}! 🎉 لدينا عرض حصري خصيصاً لك! احصل على خصم 20% على زيارتك القادمة هذا الأسبوع. اتصل بنا أو احجز عبر الإنترنت. المقاعد محدودة!`,
    emailNotConfigured: 'البريد الإلكتروني (SendGrid) غير مُهيأ. أضف مفاتيح API في .env.local لإرسال بريد حقيقي.',
    smsNotConfigured: 'الرسائل القصيرة (Twilio) غير مُهيأة. أضف مفاتيح API في .env.local لإرسال رسائل حقيقية.',
    includeCountryCode: 'أدخل رمز البلد، مثال: +962 للأردن',
    msgPlaceholder: 'رسالة من Nexora Care',
    bookingBreakdown: 'توزيع الحجوزات',
    nSelected: 'محدد',
    clearSelection: 'مسح',
    sentSuccess: 'تم الإرسال!',
    smsDelivered: 'رسالة قصيرة مُسلَّمة',
    emailsDelivered: 'بريد إلكتروني مُسلَّم',
    sendTo: 'إرسال إلى',
    allOf: 'كل',

    // Common
    loading: 'جاري التحميل…',
    error: 'خطأ',
    required: 'هذا الحقل مطلوب',
    noEmail: 'لا يوجد بريد',
    noPhone: 'لا يوجد هاتف',
    edit: 'تعديل',
    delete: 'حذف',
    add: 'إضافة',
    failedToSave: 'فشل الحفظ',
    branchNameRequired: 'اسم الفرع مطلوب',
    branchUpdated: 'تم تحديث الفرع',
    branchCreated: 'تمت إضافة الفرع',
    datesRequired: 'تواريخ البداية والنهاية مطلوبة',
    absenceRecorded: 'تم تسجيل الغياب',
    deleteRecord: 'حذف السجل',
    deleteAbsenceConfirm: 'حذف سجل الغياب هذا؟ لا يمكن التراجع.',
    searchByCustomer: 'البحث عن عميل…',
    callCompleted: 'مكتمل',
    callNoAnswer: 'لا يوجد رد',
    callFailed: 'فشل',
    day: 'يوم',
    days: 'أيام',
    recorded: 'مسجل',
    roleAdmin: 'مدير النظام',
    roleStaff: 'موظف',
    roleManager: 'مدير',
    editAbsence: 'تعديل الغياب',
    absenceUpdated: 'تم تحديث الغياب',
    search: 'بحث',
    cancelAction: 'إلغاء الحجز',
    booked: 'محجوز',
    welcome: 'مرحباً بعودتك',
    totalCollected: 'إجمالي المحصّل',
    searchPayments: 'البحث في المدفوعات…',
    method: 'طريقة الدفع',
    noPayments: 'لا توجد مدفوعات',
    rolesNav: 'الأدوار',
    rolesTitle: 'إدارة الأدوار',
    rolesSub: 'قم بتعيين أدوار للمستخدمين للتحكم في مستوى وصولهم',
    changeRole: 'تغيير الدور',
    roleChanged: 'تم تحديث الدور',
    roleChangeFailed: 'فشل تحديث الدور',
    usersInRole: 'مستخدمون',
    noUsersInRole: 'لا يوجد مستخدمون',
    confirmRoleChange: 'تغيير الدور إلى',
    thisWeek: 'هذا الأسبوع',
    thisMonth: 'هذا الشهر',
    revenueOverview: 'نظرة عامة على الإيرادات',
    avgPerAppointment: 'متوسط لكل موعد',
    unpaidInvoices: 'فواتير غير مدفوعة',
    paymentRate: 'نسبة الدفع',
    appointmentMetrics: 'مؤشرات المواعيد',
    todaysSchedule: 'مواعيد اليوم',
    noShowRate: 'نسبة الغياب',
    operations: 'العمليات',
    servicesOffered: 'الخدمات المقدمة',
    revenuePerCustomer: 'الإيراد لكل عميل',
    reportsSubtitle: 'رؤى لمركز رعايتك',
    print: 'طباعة',
    printReport: 'طباعة التقرير',

    // Calendar
    calendarNav: 'التقويم',
    revenueNav: 'الإيرادات',
  },
};

type TranslationKey = keyof typeof translations.en;

interface LanguageContextValue {
  lang: Language;
  setLang: (l: Language) => void;
  toggleLang: () => void;
  t: (key: string) => any;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextValue>({
  lang: 'en',
  setLang: () => {},
  toggleLang: () => {},
  t: (k) => k,
  isRTL: false,
});

export function LanguageProvider({ children, initialLang }: { children: React.ReactNode; initialLang?: string }) {
  const [lang, setLangState] = useState<Language>(
    initialLang === 'ar' ? 'ar' : 'en'
  );

  // Before first paint: check URL ?lang param first, then localStorage
  useIsomorphicLayoutEffect(() => {
    try {
      const urlParam = new URLSearchParams(window.location.search).get('lang');
      if (urlParam === 'ar' || urlParam === 'en') {
        setLangState(urlParam);
        localStorage.setItem('lang', urlParam);
        document.cookie = `lang=${urlParam};path=/;max-age=31536000;SameSite=Lax`;
        return;
      }
      const stored = localStorage.getItem('lang');
      if ((stored === 'ar' || stored === 'en') && stored !== lang) {
        setLangState(stored as Language);
      }
    } catch {}
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Keep <html> dir/lang in sync
  useEffect(() => {
    document.documentElement.setAttribute('dir', lang === 'ar' ? 'rtl' : 'ltr');
    document.documentElement.setAttribute('lang', lang);
  }, [lang]);

  // Save to both cookie (for SSR) and localStorage when user switches language
  const setLang = (l: Language) => {
    setLangState(l);
    try {
      localStorage.setItem('lang', l);
      document.cookie = `lang=${l};path=/;max-age=31536000;SameSite=Lax`;
    } catch {}
  };

  const toggleLang = () => setLang(lang === 'en' ? 'ar' : 'en');

  const t = (key: string): any =>
    (translations[lang] as any)[key] ?? (translations['en'] as any)[key] ?? key;

  return (
    <LanguageContext.Provider value={{ lang, setLang, toggleLang, t, isRTL: lang === 'ar' }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
